Annotations #5

diff --git a/.github/workflows/policies_rego.yaml b/.github/workflows/policies_rego.yaml
--- a/.github/workflows/policies_rego.yaml
+++ b/.github/workflows/policies_rego.yaml
@@ -31,6 +31,9 @@ jobs:
         shell: bash --noprofile --norc -o pipefail {0}
         run: |
           ./kyverno apply ./global-actions/policies/ -r ./kubernetes/kube-artifacts -p | tail -n +7 | yq -o json | jq -r ".results[] | .message" | grep error > kyverno.message
-          while read -r line; do
-            echo "error:: $line"
-          done < kyverno.message
+          if [ -s kyverno.message ]; then
+            while read -r line; do
+              echo "error:: $line"
+            done < kyverno.message
+            exit 1
+          fi
